ReSdk-ReSdk mediation
android/privacy-sandbox-samples pull request #112
Opened 2024-07-10 16:56 UTC by anaghask-google

Video link of new flow: https://b.corp.google.com/issues/341038650#comment3

2024-07-11 09:56 UTC, shiwangi-shah requested changes

2024-07-11 09:56 UTC, shiwangi-shah commented on PrivacySandboxKotlin/client-app/src/main/java/com/example/client/MainActivity.kt
> +    enum class MediationOption {
Lets add a few lines explain the different origins of medaited ads:
As SDKs transition into the SDK Runtime, we may have some SDKs still in the app process while the mediator and other SDKs have moved.
RE_RE Mediated Ads is the scenario when the winning ad network is Runtime Enables as is the Mediator.

2024-07-11 09:56 UTC, shiwangi-shah commented on PrivacySandboxKotlin/client-app/src/main/java/com/example/client/MainActivity.kt
> +        // Mediation is enabled if Runtime-Runtime Mediation option or Runtime-App Mediation
Runtime-app hasnt been introduced in the sample Ads yet. Consider rephrasing to: Mediated Ads are enables when RE-RE Mediation option is chosen

2024-07-11 09:56 UTC, shiwangi-shah commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/api/SdkBannerRequest.kt
> +     val activityLauncher: SdkActivityLauncher,
nit: remove space

2024-07-11 09:56 UTC, shiwangi-shah commented on PrivacySandboxKotlin/client-app/src/main/java/com/example/client/MainActivity.kt
> +        val mediationEnabled =
consider refactoring to requestMediatedAd

2024-07-11 09:56 UTC, shiwangi-shah commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/api/SdkService.kt
> +    suspend fun getBanner(request: SdkBannerRequest, isMediateeSdkEnabled: Boolean): SdkSandboxedUiAdapter?
Lets reuse what we choose as the variable name above

2024-07-11 09:56 UTC, shiwangi-shah commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/implementation/SdkSandboxedUiAdapterImpl.kt
> +            return View.inflate(sdkContext, R.layout.banner, null).apply {
We could explain that the mediator's View is using an SSV that is populated from the RE-Mediator which is local to the process. The mediator's View contains a child View from the mediatee and an overlay from the mediator . This will be sent to the Publisher as a SandboxedUiAdapter owned by the Mediator.

2024-07-11 09:56 UTC, shiwangi-shah commented on PrivacySandboxKotlin/example-sdk/src/main/res/layout/banner.xml
> +        <androidx.privacysandbox.ui.client.view.SandboxedSdkView
add a comment to say this SSV may get views from the local RE_SDK

2024-07-11 09:56 UTC, shiwangi-shah commented on PrivacySandboxKotlin/existing-sdk/src/main/java/com/existing/sdk/BannerAd.kt
> +        mediationEnabled: Boolean) {
lets reuse the same variable name we choose ..or, shouldLoadMediatedAd

2024-07-11 09:56 UTC, shiwangi-shah commented on PrivacySandboxKotlin/mediatee-sdk/build.gradle
> + * Copyright (C) 2022 The Android Open Source Project
Lets change all copyright years to 2024

2024-07-11 09:56 UTC, shiwangi-shah commented on PrivacySandboxKotlin/mediatee-sdk/src/main/java/com/mediatee/implementation/SdkSandboxedUiAdapterImpl.kt
> +        if (request.isWebViewBannerAd) {
have we tested both cases for the mediated ad?

2024-07-11 09:56 UTC, shiwangi-shah commented on PrivacySandboxKotlin/mediatee-sdk/src/main/java/com/mediatee/implementation/SdkServiceImpl.kt
> +    override suspend fun createFile(sizeInMb: Int): String {
do we need this?

2024-07-11 15:26 UTC, anaghask-google commented on PrivacySandboxKotlin/client-app/src/main/java/com/example/client/MainActivity.kt
> +        // Mediation is enabled if Runtime-Runtime Mediation option or Runtime-App Mediation
Done

2024-07-11 15:26 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/api/SdkBannerRequest.kt
> +     val activityLauncher: SdkActivityLauncher,
Done

2024-07-11 15:26 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/api/SdkService.kt
> +    suspend fun getBanner(request: SdkBannerRequest, isMediateeSdkEnabled: Boolean): SdkSandboxedUiAdapter?
Done

2024-07-11 15:26 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/res/layout/banner.xml
> +        <androidx.privacysandbox.ui.client.view.SandboxedSdkView
Done

2024-07-11 15:26 UTC, anaghask-google commented on PrivacySandboxKotlin/existing-sdk/src/main/java/com/existing/sdk/BannerAd.kt
> +        mediationEnabled: Boolean) {
Done

2024-07-11 15:27 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk/build.gradle
> + * Copyright (C) 2022 The Android Open Source Project
Done

2024-07-11 15:27 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk/src/main/java/com/mediatee/implementation/SdkSandboxedUiAdapterImpl.kt
> +        if (request.isWebViewBannerAd) {
Yes, both cases can be seen in the video of the new flow

2024-07-11 15:27 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk/src/main/java/com/mediatee/implementation/SdkServiceImpl.kt
> +    override suspend fun createFile(sizeInMb: Int): String {
Removed now. Thanks! :)

2024-07-12 10:23 UTC, shiwangi-shah commented on PrivacySandboxKotlin/client-app/build.gradle
> - * Copyright (C) 2022 The Android Open Source Project
these need to be 2024 only for the new files we add with this CL.

2024-07-12 10:23 UTC, shiwangi-shah commented on PrivacySandboxKotlin/client-app/src/main/java/com/example/client/MainActivity.kt
> +    // RE_RE Mediated Ads is the scenario when the winning ad network is Runtime Enables as is the
nit: typo
Runtime Enabled

2024-07-12 10:23 UTC, shiwangi-shah commented on PrivacySandboxKotlin/client-app/src/main/java/com/example/client/MainActivity.kt
> +            shouldLoadMediatedAd
lets use loadMediatedAd

2024-07-12 10:23 UTC, shiwangi-shah commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/implementation/SdkServiceImpl.kt
> +                val controller = SdkSandboxControllerCompat.from(context)
Consider adding a comment to say that an RE_SDK (in this case, the mediator) can load another SDK in the sdk runtime or if it is already loaded they may get the sdks binder from controller#getSandboxedSdks

2024-07-12 10:23 UTC, shiwangi-shah commented on PrivacySandboxKotlin/existing-sdk/src/main/java/com/existing/sdk/BannerAd.kt
> +        shouldLoadMediatedAd: Boolean) {
No op comment: I know we discussed consistency across but we can keep this here and rename the other one to loadMediatedAd..

2024-07-12 13:48 UTC, anaghask-google commented on PrivacySandboxKotlin/client-app/build.gradle
> - * Copyright (C) 2022 The Android Open Source Project
Done

2024-07-12 13:48 UTC, anaghask-google commented on PrivacySandboxKotlin/client-app/src/main/java/com/example/client/MainActivity.kt
> +    // RE_RE Mediated Ads is the scenario when the winning ad network is Runtime Enables as is the
Done

2024-07-12 13:48 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/implementation/SdkServiceImpl.kt
> +                val controller = SdkSandboxControllerCompat.from(context)
Done

2024-07-12 13:48 UTC, anaghask-google commented on PrivacySandboxKotlin/existing-sdk/src/main/java/com/existing/sdk/BannerAd.kt
> +        shouldLoadMediatedAd: Boolean) {
Done

2024-07-30 12:11 UTC, notmariazoe submitted a review, later dismissed

2024-08-01 09:34 UTC, anaghask-google commented on PrivacySandboxKotlin/client-app/src/main/java/com/example/client/MainActivity.kt
> +        // Supply the mediation_option array to the mediationDropDownMenu spinner.
Done

2024-08-05 10:13 UTC, shiwangi-shah commented on PrivacySandboxKotlin/client-app/src/main/java/com/example/client/MainActivity.kt
> +        val loadMediatedAd =
it seems the functionality would expect a banner ad click to start an activity (if shouldStartActivityPredicate is true). have we tested for that?

2024-08-05 11:19 UTC, anaghask-google commented on PrivacySandboxKotlin/client-app/src/main/java/com/example/client/MainActivity.kt
> +        val loadMediatedAd =
In this PR we didn't do it, I have made changed the wording in the mediated banner ad to not include the "click to start activity" text so it's not misleading

2024-08-06 10:00 UTC, shiwangi-shah approved these changes
LGTM. Lets test this for backward compat as well

2024-08-06 15:11 UTC, anaghask-google commented on PrivacySandboxKotlin/build.gradle
> +        agp_version = '8.6.0-alpha08'
Removed

2024-08-08 06:00 UTC, merged