Add RE Mediatee Adapter.
android/privacy-sandbox-samples pull request #121
Opened 2024-09-17 10:52 UTC by anaghask-google

Add implementation for RE Mediatee Adapter.

mediatee-adapter-sdk changes:

- implements an interface declared by Mediator. 
- Adapter sdk is loaded in Mediator (example-sdk). This invokes the SdkProvider#createSdkService code which registers the adapter with the Mediator.

example-sdk (mediator) changes:

- example-sdk communicates with Adapter, not with mediatee directly.
- example-sdk does not have a build dependency on mediatee-sdk or the mediatee-sdk-adapter.

2024-09-23 14:00 UTC, shiwangi-shah commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkProvider.kt
> +            if (loadedSandboxedSdk.getSdkInfo()!!.name == mediatorSdkName) {
possible nullpointer -lets use ? instead..

2024-09-23 14:01 UTC, shiwangi-shah commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/MediateeAdapterInterfaceImpl.kt
> +class MediateeAdapterInterfaceImpl(private val context: Context) : MediateeAdapterInterface {
Lets add doc for the purpose of this class

2024-09-23 14:46 UTC, shiwangi-shah commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/implementation/SdkProvider.kt
> +        val controller = SdkSandboxControllerCompat.from(context!!)
Lets avoid the use of !! in other parts too?

2024-09-23 15:53 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/implementation/FullscreenAdImpl.kt
> +    private var reMediateeAdapter: MediateeAdapterInterface? = null
Done - chaned to mediatee/adapter, RE by default

2024-09-23 15:53 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/implementation/FullscreenAdImpl.kt
> +            reMediateeAdapter!!.showFullscreenAd(activityLauncher)
This still gives me a compile error - Smart cast to 'MediateeAdapterInterface' is impossible, because 'mediateeAdapter' is a mutable property that could have been changed by this time

2024-09-23 15:53 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/implementation/SdkProvider.kt
> +        val controller = SdkSandboxControllerCompat.from(context!!)
Context is null until onLoadSdk is called

2024-09-23 15:53 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/implementation/SdkProvider.kt
> +        for (loadedSandboxedSdk in controller.getSandboxedSdks()) {
Done

2024-09-23 15:53 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/MediateeAdapterInterfaceImpl.kt
> +class MediateeAdapterInterfaceImpl(private val context: Context) : MediateeAdapterInterface {
Done

2024-09-23 15:53 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkProvider.kt
> +            if (loadedSandboxedSdk.getSdkInfo()!!.name == mediatorSdkName) {
Done

2024-09-24 10:26 UTC, shiwangi-shah commented
> Add implementation for RE Mediatee Adapter.

Lets please not use abbreviations

2024-09-24 10:59 UTC, shiwangi-shah commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkServiceImpl.kt
> +class SdkServiceImpl() : SdkService
why is this and empty implpementation ? add docs maybe

2024-09-24 10:59 UTC, shiwangi-shah commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkProvider.kt
> +     * Registers MediateeAdapterInterface with the Mediator.
Lets use square brackets to link [MediateeAdapterInterface]

2024-09-24 10:59 UTC, shiwangi-shah commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkProvider.kt
> +        mediatorInstance?.registerMediateeAdapter(MediateeAdapterInterfaceImpl(context!!))
when can context be null?

2024-09-24 10:59 UTC, shiwangi-shah commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkProvider.kt
> +        mediatorInstance = SdkServiceFactory.wrapToSdkService(sandboxedSdk?.getInterface()!!)
do we really want to fail with a nullpointer in case mediator isnt available? lets add checks and throw. You can probably save the checked non null variant and use it here.

2024-09-24 10:59 UTC, shiwangi-shah commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/MediateeAdapterInterfaceImpl.kt
> + * Implements MediateeAdapterInterface.
add [] to link the class

2024-09-24 10:59 UTC, shiwangi-shah commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/MediateeAdapterInterfaceImpl.kt
> + * Mediatee sdk is loaded and called to show ads.
Is this relevant here? Consider adding:
"This class has APIs that takes requests from the mediator and gets responses from the mediatee"

2024-09-24 10:59 UTC, shiwangi-shah commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/api/SdkService.kt
> + * SDK Service for the RE Adapter - which is empty for our sample.
lets not use abbreviations

2024-09-24 10:59 UTC, shiwangi-shah commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/implementation/SdkServiceImpl.kt
>          return fullscreenAd
Shouldn't we be doing more that setting the adapters here - I suppose the overall call is a loadAd which will be followed by showAd. loadAd should also ideally request mediatees to load the ad.

2024-09-24 11:01 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/api/SdkService.kt
> +     * Registers the RE mediatee adapter.
Done

2024-09-24 11:02 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/api/SdkService.kt
> + * SDK Service for the RE Adapter - which is empty for our sample.
Done

2024-09-24 11:03 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/implementation/SdkServiceImpl.kt
>          return fullscreenAd
This is done in FullscreenAdImpl

2024-09-24 14:27 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkServiceImpl.kt
> +class SdkServiceImpl() : SdkService
In this case there is no API to be exposed by annotating with PrivacySandboxCallback. I think this may be the case in a lot of cases

2024-09-24 14:27 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkProvider.kt
> +     * Registers MediateeAdapterInterface with the Mediator.
Done

2024-09-24 14:28 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkProvider.kt
> +        mediatorInstance?.registerMediateeAdapter(MediateeAdapterInterfaceImpl(context!!))
Done

2024-09-24 14:28 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkProvider.kt
> +        mediatorInstance = SdkServiceFactory.wrapToSdkService(sandboxedSdk?.getInterface()!!)
Done

2024-09-24 14:28 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/MediateeAdapterInterfaceImpl.kt
> + * Implements MediateeAdapterInterface.
Done

2024-09-24 14:28 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/MediateeAdapterInterfaceImpl.kt
> + * Mediatee sdk is loaded and called to show ads.
Done

2024-09-25 22:05 UTC, shiwangi-shah commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/implementation/FullscreenAdImpl.kt
> -        } else if (mediationType == sdkContext.getString(R.string.mediation_option_re_inapp)) {
lets change mediation options to be re_mediatee and inapp_mediatee

2024-09-25 22:11 UTC, shiwangi-shah commented on PrivacySandboxKotlin/inapp-mediatee-sdk/src/main/java/com/inappmediatee/sdk/InAppMediateeSdk.kt
> +      // This could contain more logic. For our sample this is empty.
Consider adding the reason: because the adapter caches the loaded and so, never needs to invoke the mediatee for a show call in our sample

2024-09-26 09:47 UTC, shiwangi-shah commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/api/MediateeAdapterInterface.kt
> + * Runtime-enabled Adapters will register this interface with the Mediator.
Consider changing to: Runtime-enabled Adapters will register an object that implements this interface with the Mediator

2024-09-26 09:47 UTC, shiwangi-shah commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/api/MediateeAdapterInterface.kt
> +    ): Bundle?
Should we call out what this bundle is and why is it a bundle

2024-09-26 11:11 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/api/SdkService.kt
> +     * For the Runtime-enabled Adapter case, Adapter is initialised and registered with the
Done

2024-09-26 11:11 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/api/SdkService.kt
> +     * Mediator when Mediator is initialised.
Done

2024-09-26 11:11 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/implementation/FullscreenAdImpl.kt
> -        } else if (mediationType == sdkContext.getString(R.string.mediation_option_re_inapp)) {
Done

2024-09-26 11:11 UTC, anaghask-google commented on PrivacySandboxKotlin/inapp-mediatee-sdk/src/main/java/com/inappmediatee/sdk/InAppMediateeSdk.kt
> +      // This could contain more logic. For our sample this is empty.
Changed

2024-09-26 11:11 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/api/MediateeAdapterInterface.kt
> + * Runtime-enabled Adapters will register this interface with the Mediator.
Done

2024-09-26 11:11 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/api/MediateeAdapterInterface.kt
> +    ): Bundle?
Done

2024-09-30 10:55 UTC, anaghask-google commented
> Thanks Anagha! Have we test this for backward compatibility too?

I have tested it in S and T, it works

2024-09-30 13:28 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/MediateeAdapterInterfaceImpl.kt
> +        loadMediateeSdk()
Done

2024-09-30 14:22 UTC, shiwangi-shah approved these changes
Thanks Anagha !

2024-10-09 11:47 UTC, notmariazoe requested changes
Some documentation comments - Thanks!

2024-10-09 16:37 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkProvider.kt
> +        mediatorInstance =
Since adapter is supposed to be initialised when the mediator is initialised, this shouldn't happen. I've added this

2024-10-09 16:37 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkServiceImpl.kt
> +/** Implements SdkService - which is empty for our sample. */
No APIs are exposed by adapter for our case, I don't know if there will be a case where that is needed

2024-10-09 16:37 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkProvider.kt
> +     * Registers [MediateeAdapterInterface] with the Mediator.
Done

2024-10-09 16:37 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkProvider.kt
> +     * <p>This function is called by the SDK sandbox after it loads the SDK.
Done

2024-10-09 16:37 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/implementation/SdkProvider.kt
> +     * <p>This function is called by the SDK sandbox after it loads the SDK.
Done

2024-10-09 16:37 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/implementation/SdkProvider.kt
> +     * Does the work needed for the SDK to start handling requests.
Done

2024-10-09 16:37 UTC, anaghask-google commented on PrivacySandboxKotlin/example-sdk/src/main/java/com/example/api/MediateeAdapterInterface.kt
> +     * PrivacySandboxInterface is expected to be implemented by the declaring SDK (example-sdk in
Done

2024-10-09 17:29 UTC, notmariazoe approved these changes

2024-10-09 17:30 UTC, merged