Fix: Remove thread blocking logic from SdkProvider implementation
android/privacy-sandbox-samples pull request #135
Opened 2024-12-06 12:08 UTC by anaghask-google

- Thread blocking code removed from SdkProvider implementation and added to a new initialise API in mediator (example-sdk).
- RA_SDK (existing-sdk) will call both SdkSandboxController#loadSdk("mediatorSdk") and mediatorSdkService.initialise(). This will be done by the App in the long term.

2024-12-06 13:07 UTC, shiwangi-shah commented
Lets refer to the SDKs as runtime enabled and runtime aware instead of example and existing.

2024-12-06 13:12 UTC, shiwangi-shah commented on PrivacySandboxKotlin/runtime-enabled-sdk/src/main/java/com/runtimeenabled/api/SdkService.kt
> +     * App has to call this API after loadSdk("mediator") call.
The Runtime Aware SDK calls this API to initialise the SdkService. We shouldnt tie the documentation here to its current usages.

2024-12-06 13:12 UTC, shiwangi-shah commented on PrivacySandboxKotlin/runtime-enabled-sdk/src/main/java/com/runtimeenabled/implementation/SdkServiceImpl.kt
> +    override suspend fun getMessage(): String = "Hello from Privacy Sandbox!"
consider adding runtime-enabled sdk in the message?

2024-12-06 13:17 UTC, anaghask-google commented on PrivacySandboxKotlin/runtime-enabled-sdk/src/main/java/com/runtimeenabled/implementation/SdkServiceImpl.kt
> +    override suspend fun getMessage(): String = "Hello from Privacy Sandbox!"
Done

2024-12-10 11:06 UTC, shiwangi-shah approved these changes

2024-12-11 11:21 UTC, notmariazoe requested changes
LGTM, one nit and one question.

2024-12-11 11:21 UTC, notmariazoe commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkProvider.kt
>          for (loadedSandboxedSdk in controller.getSandboxedSdks()) {
Could we encapsulate the logic below in flags that could be more human readable? I'd prefer reducing the cognitive overload for people who might not be familiar for the project.

For example, needToLoadMediator or needToLoadMediatee

2024-12-11 11:21 UTC, notmariazoe commented on PrivacySandboxKotlin/runtime-enabled-sdk/src/main/java/com/runtimeenabled/implementation/SdkServiceImpl.kt
>      private val tag = "ExampleSdk"
Is this tag still correct? IIRC we renamed it all to RE and RA

2024-12-11 13:31 UTC, anaghask-google commented on PrivacySandboxKotlin/mediatee-sdk-adapter/src/main/java/com/mediateeadapter/implementation/SdkProvider.kt
>          for (loadedSandboxedSdk in controller.getSandboxedSdks()) {
Done

2024-12-11 13:31 UTC, anaghask-google commented on PrivacySandboxKotlin/runtime-enabled-sdk/src/main/java/com/runtimeenabled/implementation/SdkServiceImpl.kt
>      private val tag = "ExampleSdk"
Done

2024-12-11 13:47 UTC, notmariazoe approved these changes
LGTM

2024-12-11 13:48 UTC, merged